# agent-suite-doctor-alert.ps1 — Windows Scheduled Task for periodic doctor + alerting
# Generated by `agent-suite schedule install`. Do not edit by hand.

$action = New-ScheduledTaskAction -Execute 'agent-suite alert-check'
$trigger = New-ScheduledTaskTrigger -DAILY -At 2am
$settings = New-ScheduledTaskSettingsSet `
  -StartWhenAvailable `
  -DontStopOnIdleEnd `
  -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 15)
Register-ScheduledTask `
  -TaskName 'agent-suite-doctor-alert' `
  -Action $action `
  -Trigger $trigger `
  -Settings $settings `
  -RunLevel Highest `
  -Force
