# Weekly full cairn chain replay; records the verdict doctor reports
# Generated by `agent-suite schedule install` — do not edit by hand.
# Re-run `agent-suite schedule install` to regenerate.
$action = New-ScheduledTaskAction -Execute 'cairn integrity'
$trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Sunday -At 2am
$settings = New-ScheduledTaskSettingsSet `
  -StartWhenAvailable `
  -DontStopOnIdleEnd `
  -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 15)
Register-ScheduledTask `
  -TaskName 'agent-suite-chain-integrity' `
  -Action $action `
  -Trigger $trigger `
  -Settings $settings `
  -RunLevel Highest `
  -Force
