# agent-suite-backup.ps1 — Windows Scheduled Task for nightly backup + verify-restore
# Generated by `agent-suite schedule install`. Do not edit by hand.
# Re-run `agent-suite schedule install` to regenerate.

$action = New-ScheduledTaskAction -Execute 'agent-suite backup --verify-restore'
$trigger = New-ScheduledTaskTrigger -DAILY -At 2am
$settings = New-ScheduledTaskSettingsSet `
  -StartWhenAvailable `
  -DontStopOnIdleEnd `
  -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 15)
Register-ScheduledTask `
  -TaskName 'agent-suite-backup' `
  -Action $action `
  -Trigger $trigger `
  -Settings $settings `
  -RunLevel Highest `
  -Force
