# Weekly restore of the latest dump into scratch + verify-restore
# Generated by `agent-suite schedule install` — do not edit by hand.
# Re-run `agent-suite schedule install` to regenerate.
try {
  $action = New-ScheduledTaskAction -Execute 'agent-suite' -Argument 'restore --dir-env AGENT_SUITE_BACKUP_DIR --dsn-env AGENT_SUITE_VERIFY_RESTORE_DSN'
  $trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Sunday -At 4am
  $settings = New-ScheduledTaskSettingsSet `
    -StartWhenAvailable `
    -DontStopOnIdleEnd `
    -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 15)
  Register-ScheduledTask `
    -TaskName 'agent-suite-restore-verify' `
    -Action $action `
    -Trigger $trigger `
    -Settings $settings `
    -RunLevel Highest `
    -Force -ErrorAction Stop | Out-Null
  $registered = Get-ScheduledTask -TaskName 'agent-suite-restore-verify' -ErrorAction Stop
  $registeredAction = @($registered.Actions)[0]
  $registeredTrigger = @($registered.Triggers)[0]
  $startBoundaryText = [string]$registeredTrigger.StartBoundary
  $startBoundaryVerified = $false
  try {
    $startBoundary = [DateTimeOffset]::Parse($startBoundaryText, [System.Globalization.CultureInfo]::InvariantCulture)
    $startBoundaryVerified = ($startBoundary.Hour -eq 4) -and ($startBoundary.Minute -eq 0)
  } catch {
    try {
      $startBoundary = [DateTimeOffset]::Parse($startBoundaryText)
      $startBoundaryVerified = ($startBoundary.Hour -eq 4) -and ($startBoundary.Minute -eq 0)
    } catch {
      $startBoundaryVerified = $false
    }
  }
  $repetitionText = [string]$registeredTrigger.Repetition.Interval
  $repetitionMinutes = $null
  if ($repetitionText) {
    try {
      $repetitionMinutes = ([System.Xml.XmlConvert]::ToTimeSpan($repetitionText)).TotalMinutes
    } catch {
      try {
        $repetitionMinutes = ([TimeSpan]::Parse($repetitionText)).TotalMinutes
      } catch {
        $repetitionMinutes = $null
      }
    }
  }
  $durationText = [string]$registeredTrigger.Repetition.Duration
  $durationMinutes = $null
  $durationVerified = -not [bool]$durationText
  if ($durationText) {
    try {
      $durationMinutes = ([System.Xml.XmlConvert]::ToTimeSpan($durationText)).TotalMinutes
    } catch {
      try {
        $durationMinutes = ([TimeSpan]::Parse($durationText)).TotalMinutes
      } catch {
        $durationMinutes = $null
      }
    }
  }
  $repetitionVerified = $null -eq $repetitionMinutes
  $actionVerified = ([string]$registeredAction.Execute -eq 'agent-suite') -and
    ([string]$registeredAction.Arguments -eq 'restore --dir-env AGENT_SUITE_BACKUP_DIR --dsn-env AGENT_SUITE_VERIFY_RESTORE_DSN')
  $triggerType = [string]$registeredTrigger.CimClass.CimClassName
  $triggerVerified = ($triggerType -eq 'MSFT_TaskWeeklyTrigger') -and $startBoundaryVerified -and $repetitionVerified -and $durationVerified
  if ('WEEKLY' -eq 'WEEKLY') {
    $triggerVerified = $triggerVerified -and
      ([string]$registeredTrigger.DaysOfWeek -match 'Sunday')
  }
  if (-not $actionVerified -or -not $triggerVerified) {
    throw "registered task action or trigger does not match the requested schedule"
  }
  [ordered]@{
    verified = $true
    task_name = [string]$registered.TaskName
    execute = [string]$registeredAction.Execute
    arguments = [string]$registeredAction.Arguments
    trigger = 'WEEKLY'
    trigger_type = $triggerType
    trigger_time = $startBoundaryText
    trigger_time_verified = $startBoundaryVerified
    repetition_interval = $repetitionText
    repetition_minutes = $repetitionMinutes
    repetition_verified = $repetitionVerified
    repetition_duration = $durationText
    repetition_duration_minutes = $durationMinutes
    repetition_duration_verified = $durationVerified
    action_verified = $actionVerified
    trigger_verified = $triggerVerified
  } | ConvertTo-Json -Compress
} catch {
  Write-Error $_
  exit 1
}
