# Periodic doctor health check + alert routing on state change
# Generated by `agent-suite schedule install` — do not edit by hand.
# Re-run `agent-suite schedule install` to regenerate.
$action = New-ScheduledTaskAction -Execute 'agent-suite' -Argument 'alert-check'
$trigger = New-ScheduledTaskTrigger -Daily -At 2am
$settings = New-ScheduledTaskSettingsSet `
  -StartWhenAvailable `
  -DontStopOnIdleEnd `
  -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 15)
Register-ScheduledTask `
  -TaskName 'agent-suite-doctor-alert' `
  -Action $action `
  -Trigger $trigger `
  -Settings $settings `
  -RunLevel Highest `
  -Force
