# Nightly pg_dump of the suite Postgres store + weekly verify-restore
# Generated by `agent-suite schedule install` — do not edit by hand.
# Re-run `agent-suite schedule install` to regenerate.
$action = New-ScheduledTaskAction -Execute 'agent-suite' -Argument 'backup --verify-restore'
$trigger = New-ScheduledTaskTrigger -Daily -At 2am
$settings = New-ScheduledTaskSettingsSet `
  -StartWhenAvailable `
  -DontStopOnIdleEnd `
  -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 15)
Register-ScheduledTask `
  -TaskName 'agent-suite-backup' `
  -Action $action `
  -Trigger $trigger `
  -Settings $settings `
  -RunLevel Highest `
  -Force
